### ISSUE TITLE
Mocha::StateMachine states method stomps on states fixture

### ISSUE THREAD

**Issue by DBugger32** [freerange/mocha#620]
Attempting to upgrade to Rails 7.1.1, and running into a namespace issue. It appears the Mocha::StateMachine collection is hijacking the states fixture.

Ruby version is 3.2.2.

After upgrading from Rails 7.0.8 to 7.1.1, I am getting this error running a test that uses the fixture named states...

`NoMethodError: undefined method `display_name' for #<Mocha::StateMachine:0x0000000143434470 @name=:robonia, @current_state=nil>`

Have a simple active record class called State, that references the states table.

There are a few fixture records we use for testing.

And a test class that exists basically to test one method of the State class

```
require 'test_helper'

class StateTest < ActiveSupport::TestCase
   fixtures :states
   it 'returns #abbreviation - #name' do
      assert_equal 'RB - Robonia', states(:robonia).display_name
   end
end
```

Here is the top of the TestHelper class...

```
ENV['RAILS_ENV'] ||= 'test'
require_relative "../config/environment"
require 'rails/test_help'
require 'minitest/autorun'
require 'mocha/minitest'
```

Realize while typing this, that it might be a class loader issue of some sort.

**Comment by floehopper** [comment]
Hmm. Mocha has implemented the [`Mocha::API#states`](https://mocha.jamesmead.org/Mocha/API.html#states-instance_method) method for many years, so something must've changed in Rails. I'm not very familiar with fixtures these days, but it looks as if Rails must be magically defining a `#states` method and somehow making that available from within the tests. I'm guessing that in Rails v7.0.8 this was happening *after* `require 'mocha/minitest'`, but in Rails v7.1.1 it's happening *before* this point.

Looking into it a bit more, [this Rails PR](https://github.com/rails/rails/pull/44528) which was [included in Rails v7.1.0.beta1](https://github.com/rails/rails/blob/7-1-stable/activerecord/CHANGELOG.md#rails-710beta1-september-13-2023) looks very suspicious. It looks like it's changed from defining the fixture accessor methods up-front to relying on a `method_missing` implementation and presumably `Mocha::API#states` is intercepting the relevant calls.

I can't immediate think of a nice way around this. Perhaps you could rename the fixture accessor somehow, e.g. rename the YML file to e.g. `my_states.yml` and either use `model_class` within the YML or [`ActiveRecord::TestFixtures::ClassMethods#set_fixture_class`](https://api.rubyonrails.org/classes/ActiveRecord/TestFixtures/ClassMethods.html#method-i-set_fixture_class) in the test to specify the model class as `State`...?

**Comment by DBugger32** [comment]
Thank you for the quick response and from saving me to having to dig into the Rails source.  Will try the suggested workarounds.  Will close the issue -- because this clearly not a mocha problem.

**Comment by floehopper** [comment]
> Thank you for the quick response and from saving me to having to dig into the Rails source.

No worries - I hope that was the relevant change!

> Will try the suggested workarounds.

Good luck! 🤞 Let me know if they work!

> Will close the issue -- because this clearly not a mocha problem.

Thanks. I think one could argue that Mocha shouldn't add a method with such a common name to the test context, but given this is the first time I've heard about this being a problem, I'm not planning to make a change at this stage.

**Comment by DBugger32** [comment]
Confess, I simply stopped using the :states fixture in the first repo. But, while bumping another app where the State class has some more meat, I had to actually implement a workaround.

1. renamed `states.yml` -> `us_states.yml`
2. added  `set_fixture_class(us_states: State)` to `class ActiveSupport::TestCase`
3. renamed all references to the :states fixture to :us_states

` let(:ct) { us_states(:CT) }`

And we're green again.

**Comment by floehopper** [comment]
@DBugger32 Cool! Thanks for letting me know! 👍

**Comment by josefarias** [comment]
Just ran into this today. I'm only planning on accessing my `states` fixtures from my system tests so was able to patch like this:

```diff
❯ git diff
diff --git a/test/application_system_test_case.rb b/test/application_system_test_case.rb
index 5960411..6645a24 100644
--- a/test/application_system_test_case.rb
+++ b/test/application_system_test_case.rb
@@ -1,3 +1,8 @@
 class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
   driven_by :selenium, using: :headless_chrome
+
+  def states(...)
+    # https://github.com/freerange/mocha/issues/620
+    access_fixture("states", ...)
+  end
 end
```

And then have my system tests inherit from `ApplicationSystemTestCase`

This is good enough for me because I don't plan to use Mocha's state machine API. But wanted to add a data point to this conversation.

FWIW, my `states` fixtures represent a collection of US states.

**Comment by floehopper** [comment]
@josefarias Thanks for posting this. I'm not sure there's much more Mocha can do about this. Since Rails is now relying on `method_missing`, I think perhaps it should include a check that the method hasn't already been defined. I'll give this some more thought.
